#!/usr/bin/env python3
import pathlib
import struct
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOUND_DIR = ROOT / "sounds"
OUT_C = ROOT / "src" / "sound_data.c"
OUT_H = ROOT / "include" / "sound_data.h"

SOUNDS = [
    ("move", "stein_faellt.mp3"),
    ("invite", "spielanfrage.mp3"),
    ("start", "start_game.mp3"),
    ("win", "you_win.mp3"),
    ("lose", "you_lose.mp3"),
]

RATE = 8000
TARGET_PEAK = 120

def decode_mp3(path):
    raw = subprocess.check_output([
        "ffmpeg", "-v", "error", "-i", str(path),
        "-ac", "1", "-ar", str(RATE), "-f", "s16le", "-"
    ])
    return list(struct.unpack("<%dh" % (len(raw) // 2), raw))

def trim_silence(samples):
    if not samples:
        return samples
    peak = max(abs(v) for v in samples)
    if peak == 0:
        return [0, 0]
    threshold = max(200, int(peak * 0.03))
    first = 0
    while first < len(samples) and abs(samples[first]) < threshold:
        first += 1
    last = len(samples) - 1
    while last > first and abs(samples[last]) < threshold:
        last -= 1
    keep = samples[first:last + 1]
    return keep if len(keep) >= 2 else [0, 0]

def normalize_to_s8(samples):
    peak = max(abs(v) for v in samples) if samples else 0
    if peak == 0:
        return [0, 0]
    out = []
    for v in samples:
        sv = int(round((v * TARGET_PEAK) / peak))
        if sv > 127:
            sv = 127
        elif sv < -128:
            sv = -128
        out.append(sv)
    if len(out) & 1:
        out.append(0)
    return out

def write_array(f, name, values):
    f.write("const BYTE sound_%s_data[] = {\n" % name)
    for i in range(0, len(values), 16):
        f.write("    ")
        f.write(", ".join(str(v) for v in values[i:i + 16]))
        if i + 16 < len(values):
            f.write(",")
        f.write("\n")
    f.write("};\n")
    f.write("const ULONG sound_%s_length = sizeof(sound_%s_data);\n\n" % (name, name))

def main():
    converted = []
    for name, filename in SOUNDS:
        samples = decode_mp3(SOUND_DIR / filename)
        trimmed = trim_silence(samples)
        values = normalize_to_s8(trimmed)
        converted.append((name, filename, len(samples), len(trimmed), values))

    with OUT_H.open("w") as f:
        f.write("#ifndef SOUND_DATA_H\n#define SOUND_DATA_H\n\n")
        f.write("#include <exec/types.h>\n")
        for name, _filename, _src_len, _trim_len, _values in converted:
            f.write("extern const BYTE sound_%s_data[];\n" % name)
            f.write("extern const ULONG sound_%s_length;\n" % name)
        f.write("\n#endif\n")

    with OUT_C.open("w") as f:
        f.write("/* Generated by tools/generate_sound_data.py. */\n")
        f.write("#include \"sound_data.h\"\n\n")
        for name, _filename, _src_len, _trim_len, values in converted:
            write_array(f, name, values)

    for name, filename, src_len, trim_len, values in converted:
        peak = max(abs(v) for v in values) if values else 0
        print("%s: %s %d -> %d samples, peak %d" % (name, filename, src_len, len(values), peak))

if __name__ == "__main__":
    main()
